import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import catalog from "../../shared/catalog.json";
import care from "../../shared/care.json";
import { money } from "@/lib/money";
import { Button } from "@/components/ui/button";

export default function Purchase() {
  const { planId } = useParams();
  const plan = catalog.find(p => p.id === planId);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [serviceMode, setServiceMode] = useState("independent");
  if (!plan) return <section className="pt-32 p-6"><h1>Paquete no encontrado</h1><Link to="/#precios">Ver paquetes</Link></section>;
  return <section className="pt-32 pb-20 px-6 max-w-3xl mx-auto"><p className="section-kicker">1. Tu proyecto</p><h1 className="text-4xl font-bold mb-5">{plan.name}</h1><p className="text-3xl font-bold mb-6">{money(plan.price)} ARS · desarrollo del alcance base</p><ul className="space-y-3 mb-6">{plan.features.map(f => <li key={f}>✓ {f}</li>)}</ul><p className="text-muted-foreground mb-6">Incluye una instancia inicial para definir público, oferta y mensaje, y acompañamiento durante el desarrollo. Comprás exclusivamente el alcance detallado. Luego del pago, verificamos la operación y coordinamos el inicio y el cronograma. Las ampliaciones requieren una propuesta adicional.</p>
    <form className="space-y-5" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); const data = new FormData(e.currentTarget); try { const r = await fetch("/api/checkout", {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({planId:plan.id,email:data.get("email"),serviceMode})}); const result = await r.json(); if (!r.ok || !result.url) throw new Error(); const url = new URL(result.url); if (url.protocol !== "https:" || !["www.mercadopago.com.ar","sandbox.mercadopago.com.ar"].includes(url.hostname)) throw new Error(); window.location.assign(url.href); } catch {setError("No pudimos abrir el pago. Podés contactarnos para coordinar la compra; no se realizó ningún cobro desde este formulario.");} finally {setBusy(false);} }}>
    <fieldset className="space-y-4"><legend className="text-2xl font-bold mb-4">2. Elegí cómo seguir después del lanzamiento</legend>
      <label className={`flex items-start gap-3 p-5 border rounded-xl cursor-pointer ${serviceMode === "independent" ? "border-primary" : "border-border"}`}><input className="mt-1" type="radio" name="serviceMode" value="independent" checked={serviceMode === "independent"} onChange={() => setServiceMode("independent")}/><span><strong className="block mb-2">Entrega independiente · sin abono</strong><span className="text-sm text-muted-foreground">Dominio y hosting se pagan aparte. Modificaciones posteriores bajo presupuesto. {plan.id === "landing" ? "Los cambios de la landing los realizamos nosotros." : "Incluye panel de administración y capacitación."}</span></span></label>
      <label className={`flex items-start gap-3 p-5 border rounded-xl cursor-pointer ${serviceMode === "care" ? "border-primary" : "border-border"}`}><input className="mt-1" type="radio" name="serviceMode" value="care" checked={serviceMode === "care"} onChange={() => setServiceMode("care")}/><span><strong className="block mb-2">Cuidado mensual · {money(care.price)} ARS/mes</strong><span className="text-sm text-muted-foreground">Desde el mes siguiente a la publicación. Hosting y dominio estándar, hasta tres solicitudes y tres horas totales al mes entre cambios y soporte. Sin permanencia mínima, con traspaso estándar incluido.</span></span></label>
    </fieldset>
    {serviceMode === "care" && <details className="border rounded-xl p-4"><summary className="font-bold cursor-pointer">Condiciones del cuidado mensual</summary><div className="text-sm text-muted-foreground space-y-3 mt-4"><p>Solicitudes y horas no acumulables. Nuevas páginas, funcionalidades e integraciones se cotizan aparte.</p><p>{care.domain}</p><p>{care.hosting}</p><p>{care.cancellation}</p><p>{care.backup}</p></div></details>}
    <div className="rounded-xl bg-secondary p-5" aria-live="polite"><p className="font-bold text-xl">Hoy pagás {money(plan.price)} ARS</p><p className="text-sm mt-2">{serviceMode === "care" ? "El cuidado mensual se coordina y factura por separado desde el mes siguiente a publicar. Este checkout no activa débitos automáticos ni cobra mensualidades por adelantado." : "Pago único por el desarrollo. No contratás mantenimiento mensual."}</p><p className="text-sm text-muted-foreground mt-3">Dominio y hosting se pagan aparte con entrega independiente, o se incluyen según las condiciones del cuidado mensual. Plataformas, licencias, comisiones de cobro, publicidad e identidad visual completa no están incluidos.</p></div>
    <label className="block">Email para la compra<input className="block w-full mt-2 p-3 rounded border bg-card" name="email" type="email" required maxLength={254} autoComplete="email" /></label>
    <label className="flex items-start gap-3 text-sm"><input type="checkbox" required className="mt-1"/><span>Leí el alcance, los costos adicionales y los <Link className="underline" to="/terms-of-service" target="_blank" rel="noopener noreferrer">términos del servicio</Link> y la <Link className="underline" to="/privacy-policy" target="_blank" rel="noopener noreferrer">política de privacidad</Link>.</span></label>
    <Button disabled={busy} type="submit" size="lg" className="w-full sm:w-auto whitespace-normal h-auto min-h-12">{busy ? "Abriendo Mercado Pago…" : "Pagar el desarrollo con Mercado Pago"}</Button><p role="alert">{error}</p></form><a className="inline-block underline mt-5" href={`https://wa.me/5493512954849?text=${encodeURIComponent(`Hola, quiero consultar por ${plan.name} de ${money(plan.price)} ARS, con ${serviceMode === "care" ? `cuidado mensual de ${money(care.price)} ARS` : "entrega independiente"}.`)}`}>Consultar antes de comprar</a>
  </section>;
}
