import { Text, LocalizedAnchor } from "@/lib/language";
import care from "../../shared/care.json";
import { money } from "@/lib/money";
const sections = [
    ['Qué contratás', 'Latam Leap diseña y desarrolla landings, webs profesionales, tiendas online y soluciones digitales a medida. La compra directa cubre únicamente el alcance base indicado en la página del paquete. Incluye una instancia inicial para definir público, oferta y mensaje, y acompañamiento durante el desarrollo. Las ampliaciones se presupuestan por separado antes de realizarlas.'],
    ['Precios y pagos', 'Los importes publicados están expresados en pesos argentinos y son precios de partida. El checkout cobra solo el desarrollo del alcance base. El proyecto comienza después de verificar la aprobación del pago y coordinar el inicio. Si elegís cuidado mensual, se coordina y factura aparte desde el mes siguiente a la publicación. La compra inicial no activa débitos automáticos.'],
    ['Entrega independiente', 'No incluye abono de mantenimiento. Dominio y hosting se pagan aparte. Las modificaciones posteriores requieren presupuesto. Web profesional y tienda incluyen panel y capacitación; en la landing, los cambios los realizamos nosotros.'],
    ['Cuidado mensual', `El abono es de ${money(care.price)} ARS por mes. Incluye hasta tres solicitudes y un máximo conjunto de tres horas mensuales entre cambios y soporte técnico. Incluye cambios de textos, imágenes, datos y ajustes sobre funcionalidades existentes. Las horas y solicitudes no se acumulan. Nuevas páginas, rediseños, integraciones y excedentes se presupuestan previamente.`],
    ['Dominio y hosting incluidos', care.domain + ' ' + care.hosting],
    ['Baja del cuidado mensual', care.cancellation + ' Desde la baja, el cliente asume los costos del nuevo proveedor. ' + care.backup],
    ['Otros costos', 'Abonos de plataforma, licencias, comisiones de cobro y publicidad no están incluidos. Identidad visual completa y campañas de marketing requieren una propuesta adicional.'],
    ['Contenido, revisiones y entrega', 'El cliente proporciona la información, los materiales y los accesos necesarios, y confirma que puede utilizarlos. Incluimos dos rondas de ajustes dentro del alcance base. El cronograma se acuerda al recibir los materiales; las ampliaciones de alcance pueden modificarlo.'],
    ['Resultados', 'La configuración SEO inicial prepara el sitio para su rastreo y comprensión. No garantiza posiciones en Google, un volumen de visitas ni resultados de ventas. Las herramientas de terceros tienen sus propias condiciones y costos.'],
    ['Cancelaciones y consultas', 'Para solicitar una cancelación, devolución o ejercer los derechos que correspondan, escribí a hola@latamleap.com e identificá la compra. Estas condiciones no limitan los derechos establecidos por la legislación aplicable.']
];
export default function TermsOfService() { return <section className="pt-32 pb-20 px-6 max-w-3xl mx-auto"><h1 className="text-4xl font-bold mb-8"><Text value={"T\u00E9rminos del servicio"}/></h1><p className="text-muted-foreground mb-8"><Text value={"Actualizados el 6 de octubre de 2026."}/></p>{sections.map(([title, text]) => <div key={title} className="mb-8"><h2 className="text-2xl font-bold mb-3"><Text value={title}/></h2><p className="text-muted-foreground leading-relaxed"><Text value={text}/></p></div>)}<LocalizedAnchor className="underline" href="mailto:hola@latamleap.com"><Text value={"hola@latamleap.com"}/></LocalizedAnchor></section>; }
