import { useId, useState, FormEvent } from "react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
interface Props { showIndustry?: boolean; buttonText?: string; showWhatsAppAlt?: boolean; }
export default function AuditForm({buttonText="Preparar consulta",showWhatsAppAlt=true}: Props) {
 const id=useId();const [message,setMessage]=useState("");
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);const text=`Hola, soy ${String(data.get('name')).trim()}. Necesito: ${data.get('solution')}. Mi proyecto: ${String(data.get('project')).trim()}.`;setMessage(text);};
 const cls="block w-full mt-2 p-3 border border-border rounded-lg bg-card text-foreground";
 return <form onSubmit={submit} className="space-y-5"><label htmlFor={id+'name'} className="block text-sm">Nombre<input id={id+'name'} name="name" autoComplete="name" required maxLength={100} className={cls}/></label><label htmlFor={id+'solution'} className="block text-sm">¿Qué necesitás?<select id={id+'solution'} name="solution" className={cls}><option>Una landing</option><option>Una Web profesional</option><option>Una tienda online</option><option>Marketing o marca</option><option>Una solución a medida</option><option>Necesito orientación</option></select></label><label htmlFor={id+'project'} className="block text-sm">Contanos sobre tu proyecto<textarea id={id+'project'} name="project" required maxLength={1500} rows={4} className={cls} placeholder="Qué vendés, qué querés resolver y si ya tenés una web"/></label><p className="text-xs text-muted-foreground">Prepararemos un mensaje para que lo envíes por WhatsApp. Consultá nuestra <Link to="/privacy-policy" className="underline">política de privacidad</Link>.</p><Button type="submit" className="w-full">{buttonText}</Button>{message && <div role="status" className="border rounded-lg p-4 space-y-3"><p>Tu consulta está preparada. Enviá el mensaje para que podamos recibirla.</p><a className="underline font-bold" href={'https://wa.me/5493512954849?text='+encodeURIComponent(message)} target="_blank" rel="noopener noreferrer">Enviar consulta por WhatsApp →</a></div>}{showWhatsAppAlt && <a className="block text-sm underline text-center" href="https://wa.me/5493512954849" target="_blank" rel="noopener noreferrer">Prefiero escribir directamente</a>}</form>;
}
